---
title: "💥 Reagenti"
format: html
toc: true
toc-depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#library(icon)
library(kableExtra)
library(formattable)
library(dplyr)
```

```{r include=FALSE}

# loading the main table from csv
lista_reagenti <- read.csv2("reagenti_110326.csv", header = TRUE)

# filtering for Lab
#lista <- subset(lista_tot, lab=="E1.20")

colnames(lista_reagenti) <- c("Nome", "Codice", "Produttore", "Peso", "Quantità", "Note", "Lab", "Posiz.", "filtro_nome", "filtro_shelf", "filtro_posizione", "CAS", "SDS", "Pericolo")

subset_by_letter <- function(data, letter) {
  output <- subset(data, filtro_nome == letter)
  return(output)
}

tab_reagenti <- function(input) {

  names(input) <- make.names(names(input), unique = TRUE)

  input %>%
    #mutate(SDS = cell_spec("SDS", "html", link = SDS)) %>%
    mutate(SDS = sprintf('<a href="%s">SDS</a>', SDS)) %>%
    select(-c(2,3,4,5,6,9,10,11)) %>%
    select(Nome, Lab, Posiz., CAS, SDS, Pericolo) %>% 
    mutate(Pericolo = recode(Pericolo,
                         "alto" = "🔴",
                         "medio" = "🟠",
                         "basso" = "🟢")) %>% 
    kable(row.names = FALSE, align = "l", "html", escape = FALSE) %>%
    kable_styling(
      bootstrap_options = c("striped", "hover", "responsive", "condensed"),
      font_size = 16
    )
}


letter_A <- subset_by_letter(lista_reagenti, "A")
letter_B <- subset_by_letter(lista_reagenti, "B")
letter_C <- subset_by_letter(lista_reagenti, "C")
letter_D <- subset_by_letter(lista_reagenti, "D")
letter_E <- subset_by_letter(lista_reagenti, "E")
letter_F <- subset_by_letter(lista_reagenti, "F")
letter_G <- subset_by_letter(lista_reagenti, "G")
letter_H <- subset_by_letter(lista_reagenti, "H")
letter_I <- subset_by_letter(lista_reagenti, "I")
letter_J <- subset_by_letter(lista_reagenti, "J")
letter_K <- subset_by_letter(lista_reagenti, "K")
letter_L <- subset_by_letter(lista_reagenti, "L")
letter_M <- subset_by_letter(lista_reagenti, "M")
letter_N <- subset_by_letter(lista_reagenti, "N")
letter_O <- subset_by_letter(lista_reagenti, "O")
letter_P <- subset_by_letter(lista_reagenti, "P")
letter_Q <- subset_by_letter(lista_reagenti, "Q")
letter_R <- subset_by_letter(lista_reagenti, "R")
letter_S <- subset_by_letter(lista_reagenti, "S")
letter_T <- subset_by_letter(lista_reagenti, "T")
letter_U <- subset_by_letter(lista_reagenti, "U")
letter_V <- subset_by_letter(lista_reagenti, "V")
letter_W <- subset_by_letter(lista_reagenti, "W")
letter_X <- subset_by_letter(lista_reagenti, "X")
letter_Y <- subset_by_letter(lista_reagenti, "Y")
letter_Z <- subset_by_letter(lista_reagenti, "Z")


```

Lista dei reagenti presenti e disponibili in laboratorio.

### Ultimo aggiornamento: 01 / 04 / 2026

------------------------------------------------------------------------

### Ultime modifiche:

- 01/04/2026 - Aggiunta pdf SDS e aggiornamento Pericoli - **Mauro**

- 12/03/2026 - Creazione lista - **Mauro**

------------------------------------------------------------------------

## A

```{r echo=FALSE}

tab_reagenti(letter_A)

```

## B

```{r echo=FALSE}

tab_reagenti(letter_B)

```

## C

```{r echo=FALSE}

tab_reagenti(letter_C)

```

## D

```{r echo=FALSE}

tab_reagenti(letter_D)

```

## E

```{r echo=FALSE}

tab_reagenti(letter_E)

```

## F

```{r echo=FALSE}

tab_reagenti(letter_F)

```

## G

```{r echo=FALSE}

tab_reagenti(letter_G)

```

## H

```{r echo=FALSE}

tab_reagenti(letter_H)

```

## I

```{r echo=FALSE}

tab_reagenti(letter_I)

```

## J

```{r echo=FALSE}

tab_reagenti(letter_J)

```

## K

```{r echo=FALSE}

tab_reagenti(letter_K)

```

## L

```{r echo=FALSE}

tab_reagenti(letter_L)

```

## M

```{r echo=FALSE}

tab_reagenti(letter_M)

```

## N

```{r echo=FALSE}

tab_reagenti(letter_N)

```

## O

```{r echo=FALSE}

tab_reagenti(letter_O)

```

## P

```{r echo=FALSE}

tab_reagenti(letter_P)

```

## Q

```{r echo=FALSE}

tab_reagenti(letter_Q)

```

## R

```{r echo=FALSE}

tab_reagenti(letter_R)

```

## S

```{r echo=FALSE}

tab_reagenti(letter_S)

```

## T

```{r echo=FALSE}

tab_reagenti(letter_T)

```

## U

```{r echo=FALSE}

tab_reagenti(letter_U)

```

## V

```{r echo=FALSE}

tab_reagenti(letter_V)

```

## W

```{r echo=FALSE}

tab_reagenti(letter_W)

```

## X

```{r echo=FALSE}

tab_reagenti(letter_X)

```

## Y

```{r echo=FALSE}

tab_reagenti(letter_Y)

```

## Z

```{r echo=FALSE}

tab_reagenti(letter_Z)

```